version: "2"
services:

  translation:
    image: "apertium"
    user: "node"
    container_name: "translation"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "8443:8443"
    expose:
      - "8443"
    command: "npm start"
    networks:
      - shopnetwork

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
  shopnetwork:

